name: thai_number_words
description: "Thai number-to-words utilities: baht text, integers, decimals, fractions, digit-by-digit, Thai/Arabic numerals, and Roman numerals."
version: 0.1.1
homepage: https://github.com/Kidpech-code/numeric_to_words
repository: https://github.com/Kidpech-code/numeric_to_words
issue_tracker: https://github.com/Kidpech-code/numeric_to_words/issues

environment:
  sdk: ^3.8.1

topics:
  - thai
  - number-to-words
  - baht
  - numerals
  - roman-numerals

dependencies:
  # No runtime dependencies.

dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

