import '../domain/currency.dart';

/// Built-in English and Thai currency names for common currency codes.
class CurrencyRegistry {
  /// Currency units keyed by uppercase three-letter code, such as `USD`.
  ///
  /// This map is mutable, so applications can add or replace entries.
  static final Map<String, CurrencyUnit> byCode = {
    // Common examples
    'USD': const CurrencyUnit(
      code: 'USD',
      englishSingular: 'dollar',
      englishPlural: 'dollars',
      thaiName: 'ดอลลาร์สหรัฐ',
      englishMinorSingular: 'cent',
      englishMinorPlural: 'cents',
      thaiMinorName: 'เซนต์',
    ),
    'THB': const CurrencyUnit(
      code: 'THB',
      englishSingular: 'baht',
      englishPlural: 'baht',
      thaiName: 'บาท',
      englishMinorSingular: 'satang',
      englishMinorPlural: 'satang',
      thaiMinorName: 'สตางค์',
    ),
    'JPY': const CurrencyUnit(
      code: 'JPY',
      englishSingular: 'yen',
      englishPlural: 'yen',
      thaiName: 'เยน',
      minorUnitDigits: 0,
    ),
    'EUR': const CurrencyUnit(
      code: 'EUR',
      englishSingular: 'euro',
      englishPlural: 'euros',
      thaiName: 'ยูโร',
      englishMinorSingular: 'cent',
      englishMinorPlural: 'cents',
      thaiMinorName: 'เซนต์',
    ),
    'GBP': const CurrencyUnit(
      code: 'GBP',
      englishSingular: 'pound',
      englishPlural: 'pounds',
      thaiName: 'ปอนด์สเตอร์ลิง',
      englishMinorSingular: 'pence',
      englishMinorPlural: 'pence',
      thaiMinorName: 'เพนนี',
    ),
    'CNY': const CurrencyUnit(
      code: 'CNY',
      englishSingular: 'renminbi',
      englishPlural: 'renminbi',
      thaiName: 'หยวนเหรินหมินปี้',
      englishMinorSingular: 'fen',
      englishMinorPlural: 'fen',
      thaiMinorName: 'เฟิน',
    ),
    'KRW': const CurrencyUnit(
      code: 'KRW',
      englishSingular: 'won',
      englishPlural: 'won',
      thaiName: 'วอน',
      minorUnitDigits: 0,
    ),
    'VND': const CurrencyUnit(
      code: 'VND',
      englishSingular: 'dong',
      englishPlural: 'dong',
      thaiName: 'ดอง',
      minorUnitDigits: 0,
    ),
    'LAK': const CurrencyUnit(
      code: 'LAK',
      englishSingular: 'kip',
      englishPlural: 'kip',
      thaiName: 'กีบ',
      englishMinorSingular: 'aht',
      englishMinorPlural: 'aht',
      thaiMinorName: 'อัด',
    ),
    'KWD': const CurrencyUnit(
      code: 'KWD',
      englishSingular: 'dinar',
      englishPlural: 'dinars',
      thaiName: 'ดีนาร์คูเวต',
      englishMinorSingular: 'fils',
      englishMinorPlural: 'fils',
      thaiMinorName: 'ฟิลส์',
      minorUnitDigits: 3,
    ),
    'SAR': const CurrencyUnit(
      code: 'SAR',
      englishSingular: 'riyal',
      englishPlural: 'riyals',
      thaiName: 'ริยัลซาอุดีอาระเบีย',
      englishMinorSingular: 'halala',
      englishMinorPlural: 'halalas',
      thaiMinorName: 'ฮาลาลา',
    ),
    'HKD': const CurrencyUnit(
      code: 'HKD',
      englishSingular: 'dollar',
      englishPlural: 'dollars',
      thaiName: 'ดอลลาร์ฮ่องกง',
      englishMinorSingular: 'cent',
      englishMinorPlural: 'cents',
      thaiMinorName: 'เซนต์',
    ),
    'SGD': const CurrencyUnit(
      code: 'SGD',
      englishSingular: 'dollar',
      englishPlural: 'dollars',
      thaiName: 'ดอลลาร์สิงคโปร์',
      englishMinorSingular: 'cent',
      englishMinorPlural: 'cents',
      thaiMinorName: 'เซนต์',
    ),
    'AUD': const CurrencyUnit(
      code: 'AUD',
      englishSingular: 'dollar',
      englishPlural: 'dollars',
      thaiName: 'ดอลลาร์ออสเตรเลีย',
      englishMinorSingular: 'cent',
      englishMinorPlural: 'cents',
      thaiMinorName: 'เซนต์',
    ),
    'CAD': const CurrencyUnit(
      code: 'CAD',
      englishSingular: 'dollar',
      englishPlural: 'dollars',
      thaiName: 'ดอลลาร์แคนาดา',
      englishMinorSingular: 'cent',
      englishMinorPlural: 'cents',
      thaiMinorName: 'เซนต์',
    ),
    'NZD': const CurrencyUnit(
      code: 'NZD',
      englishSingular: 'dollar',
      englishPlural: 'dollars',
      thaiName: 'ดอลลาร์นิวซีแลนด์',
      englishMinorSingular: 'cent',
      englishMinorPlural: 'cents',
      thaiMinorName: 'เซนต์',
    ),
  };
}
